import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import Papa from "papaparse";

const LOCALES = ["en", "ja", "ko", "zh-CN"];
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const sourcePath = path.join(root, "client", "src", "i18n", "translations.csv");
const outputPath = path.join(root, "client", "src", "i18n", "generated.ts");
const nativeOutputPath = path.join(root, "client", "electron", "nativeMessages.ts");
const nativePrefix = "native.";

function placeholders(value) {
  return [...value.matchAll(/{{\s*([A-Za-z][A-Za-z0-9]*)\s*}}/g)]
    .map((match) => match[1])
    .sort();
}

function fail(message) {
  throw new Error(`translations.csv: ${message}`);
}

const source = await readFile(sourcePath, "utf8");
if (!source.startsWith("\uFEFF")) fail("must use a UTF-8 BOM for spreadsheet compatibility");
if (/(?<!\r)\n/.test(source)) fail("must use CRLF line endings");
const csv = source
  .replace(/^\uFEFF/, "")
  .replace(/\r\n?/g, "\n");
const parsed = Papa.parse(csv, {
  header: true,
  skipEmptyLines: "greedy",
  transformHeader: (header) => header.trim()
});

if (parsed.errors.length) {
  const issue = parsed.errors[0];
  fail(`row ${Number(issue.row ?? 0) + 2}: ${issue.message}`);
}

const expectedHeaders = ["key", ...LOCALES];
const actualHeaders = parsed.meta.fields ?? [];
if (JSON.stringify(actualHeaders) !== JSON.stringify(expectedHeaders)) {
  fail(`expected headers ${expectedHeaders.join(", ")}; received ${actualHeaders.join(", ")}`);
}

const seen = new Set();
const nativeKeys = [];
const resources = Object.fromEntries(LOCALES.map((locale) => [locale, {}]));
for (const [index, row] of parsed.data.entries()) {
  const line = index + 2;
  const key = row.key?.trim();
  if (!key) fail(`row ${line} has no key`);
  if (seen.has(key)) fail(`row ${line} duplicates key ${key}`);
  seen.add(key);

  const sourcePlaceholders = placeholders(row.en ?? "");
  for (const locale of LOCALES) {
    const value = row[locale];
    if (typeof value !== "string" || value.trim() === "") {
      fail(`row ${line} (${key}) has no ${locale} translation`);
    }
    const localePlaceholders = placeholders(value);
    if (JSON.stringify(localePlaceholders) !== JSON.stringify(sourcePlaceholders)) {
      fail(`row ${line} (${key}) has mismatched ${locale} placeholders`);
    }
    resources[locale][key] = value;
  }
  if (key.startsWith(nativePrefix)) {
    const nativeKey = key.slice(nativePrefix.length);
    if (!nativeKey) fail(`row ${line} has an empty native message key`);
    nativeKeys.push(nativeKey);
  }
}

if (!seen.size) fail("contains no translation rows");
if (!nativeKeys.length) fail("contains no native message rows");

const generated = `// Generated by client/scripts/generate-locales.mjs from translations.csv. Do not edit.\n` +
  `export const localeResources = ${JSON.stringify(
    Object.fromEntries(LOCALES.map((locale) => [locale, { translation: resources[locale] }])),
    null,
    2
  )} as const;\n\n` +
  `export type MessageKey = keyof typeof localeResources.en.translation;\n` +
  `type PluralBase<Key> = Key extends \`${"${infer Base}"}_one\` | \`${"${infer Base}"}_other\` ? Base : never;\n` +
  `export type TranslationKey = MessageKey | PluralBase<MessageKey>;\n`;

const nativeResources = Object.fromEntries(
  LOCALES.map((locale) => [
    locale,
    Object.fromEntries(nativeKeys.map((key) => [key, resources[locale][`${nativePrefix}${key}`]]))
  ])
);
const generatedNative = `// Generated by client/scripts/generate-locales.mjs from translations.csv. Do not edit.\n` +
  `export type AppLocale = ${LOCALES.map((locale) => JSON.stringify(locale)).join(" | ")};\n` +
  `export type NativeMessage = ${nativeKeys.map((key) => JSON.stringify(key)).join(" | ")};\n\n` +
  `export const nativeMessages: Record<AppLocale, Record<NativeMessage, string>> = ${JSON.stringify(nativeResources, null, 2)};\n`;

function normalizeLineEndings(value) {
  return value.replace(/\r\n?/g, "\n");
}

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = await readFile(outputPath, "utf8");
  } catch {
    // The error below explains how to create the missing generated file.
  }
  if (normalizeLineEndings(current) !== generated) {
    fail("generated.ts is stale; run npm run i18n:generate");
  }
  let currentNative = "";
  try {
    currentNative = await readFile(nativeOutputPath, "utf8");
  } catch {
    // The error below explains how to create the missing generated file.
  }
  if (normalizeLineEndings(currentNative) !== generatedNative) {
    fail("nativeMessages.ts is stale; run npm run i18n:generate");
  }
  console.log(`Validated ${seen.size} localization keys and ${nativeKeys.length} native messages across ${LOCALES.length} locales.`);
} else {
  await writeFile(outputPath, generated, "utf8");
  await writeFile(nativeOutputPath, generatedNative, "utf8");
  console.log(`Generated ${seen.size} localization keys and ${nativeKeys.length} native messages across ${LOCALES.length} locales.`);
}
