import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const COMPONENTS = ["client", "service"];
const RELEASES = ["major", "minor", "patch"];
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = path.join(root, "versions.json");
const packagePath = path.join(root, "package.json");
const servicePath = path.join(root, "service", "src", "_version.py");

// Core semver without build metadata: electron-builder rejects "+" in a
// Windows product version, so the package cannot carry one anyway.
const SEMVER =
  /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$/;

function fail(message) {
  throw new Error(`versions.json: ${message}`);
}

async function readVersions() {
  let parsed;
  try {
    parsed = JSON.parse(await readFile(sourcePath, "utf8"));
  } catch (error) {
    fail(`cannot be read as JSON (${error.message})`);
  }
  const actual = Object.keys(parsed);
  if (JSON.stringify(actual) !== JSON.stringify(COMPONENTS)) {
    fail(`expected keys ${COMPONENTS.join(", ")}; received ${actual.join(", ")}`);
  }
  for (const component of COMPONENTS) {
    const value = parsed[component];
    if (typeof value !== "string" || !SEMVER.test(value)) {
      fail(`${component} version ${JSON.stringify(value)} is not semver`);
    }
  }
  return parsed;
}

function renderService(version) {
  return (
    `# Generated by scripts/version.mjs from versions.json. Do not edit.\n` +
    `__version__ = ${JSON.stringify(version)}\n`
  );
}

// A targeted replace, not JSON.stringify: package.json keeps hand-written
// single-line arrays in its electron-builder block that a reserialize destroys.
function renderPackage(source, version) {
  const pattern = /^(\s*"version"\s*:\s*")[^"]*(")/m;
  const matches = source.match(/^\s*"version"\s*:/gm) ?? [];
  if (matches.length !== 1) {
    fail(`package.json must hold exactly one version field; found ${matches.length}`);
  }
  return source.replace(pattern, `$1${version}$2`);
}

function normalizeLineEndings(value) {
  return value.replace(/\r\n?/g, "\n");
}

async function writeVersions(versions) {
  await writeFile(sourcePath, `${JSON.stringify(versions, null, 2)}\n`, "utf8");
}

async function generate(versions, { check }) {
  const packageSource = await readFile(packagePath, "utf8");
  const packageNext = renderPackage(packageSource, versions.client);
  const serviceNext = renderService(versions.service);

  if (!check) {
    await writeFile(packagePath, packageNext, "utf8");
    await writeFile(servicePath, serviceNext, "utf8");
    console.log(
      `Applied client ${versions.client} to package.json and service ${versions.service} to service/src/_version.py.`
    );
    return;
  }

  if (normalizeLineEndings(packageSource) !== normalizeLineEndings(packageNext)) {
    fail(`package.json version is not ${versions.client}; run npm run version:generate`);
  }
  let serviceCurrent = "";
  try {
    serviceCurrent = await readFile(servicePath, "utf8");
  } catch {
    // The error below explains how to create the missing generated file.
  }
  if (normalizeLineEndings(serviceCurrent) !== serviceNext) {
    fail(`service/src/_version.py is stale; run npm run version:generate`);
  }
  console.log(`Validated client ${versions.client} and service ${versions.service}.`);
}

function bumped(version, release) {
  const [core] = version.split("-");
  const [major, minor, patch] = core.split(".").map(Number);
  if (release === "major") return `${major + 1}.0.0`;
  if (release === "minor") return `${major}.${minor + 1}.0`;
  return `${major}.${minor}.${patch + 1}`;
}

function usage() {
  console.error(
    [
      "Usage:",
      "  node scripts/version.mjs                       apply versions.json",
      "  node scripts/version.mjs --check               fail if outputs are stale",
      "  node scripts/version.mjs set <component> <x.y.z>",
      "  node scripts/version.mjs bump <component> <major|minor|patch>",
      "",
      `Components: ${COMPONENTS.join(", ")}`,
    ].join("\n")
  );
}

const [command, component, value] = process.argv.slice(2);

if (command === "set" || command === "bump") {
  if (!COMPONENTS.includes(component)) {
    usage();
    process.exit(2);
  }
  const versions = await readVersions();
  let next;
  if (command === "set") {
    if (!SEMVER.test(value ?? "")) {
      usage();
      process.exit(2);
    }
    next = value;
  } else {
    if (!RELEASES.includes(value)) {
      usage();
      process.exit(2);
    }
    next = bumped(versions[component], value);
  }
  const previous = versions[component];
  versions[component] = next;
  await writeVersions(versions);
  await generate(versions, { check: false });
  console.log(`${component}: ${previous} -> ${next}`);
} else if (command === undefined || command === "--check") {
  const versions = await readVersions();
  await generate(versions, { check: command === "--check" });
} else {
  usage();
  process.exit(2);
}
